### ISSUE TITLE
No way to set group header color

### ISSUE THREAD

**Issue by jollygreenegiant** [JamalMulla/ComposePrefs#1]
Individual preferences have a `textColor` parameter, but it looks like the `prefsGroup` doesn't have that, and defaults to `MaterialTheme.colors.primary`.  It would be nice to be able to control this color as well.

**Comment by jollygreenegiant** [comment]
Same goes for content color of the ListPref dialog - it's defaulting to MaterialTheme, it would be nice to be able to theme it to match the app.

**Comment by JamalMulla** [comment]
Thanks for bringing this up. It was a bit fragile and I've improved how the GroupHeader can be included. Will be much easier to add new params in the future.
