### ISSUE TITLE
Large list of single or multiselects don't scroll

### ISSUE THREAD

**Issue by sschueller** [JamalMulla/ComposePrefs#5]
Thank you for this module.  It makes settings in composable a breeze :)

I noticed that if I have a large set of items they do not scroll making it impossible to get to all of them. I have included a screenshot.
![Screenshot_20220122-142323797 - Copy](https://user-images.githubusercontent.com/1180107/150640363-1507bb61-dd4d-47ee-ad0b-b5b7382fce01.png)
![Screenshot_20220122-142329852 - Copy](https://user-images.githubusercontent.com/1180107/150640364-79d0ec93-4476-4b90-b8b0-b0058653769b.png)

**Comment by JamalMulla** [comment]
Hi @sschueller, I'm glad this library has been useful to you. Thanks for bringing this issue to my attention. It should now be fixed in 1.0.2. If you notice any more issues, please do bring them up. Thanks.

**Comment by sschueller** [comment]
Thank you for the quick fix. works great.
